// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrLWQfzJg8QyBO5piI7uxH-eo7lFDyws',
    appId: '1:998694748532:android:52a958a3d0dca48b1bac21',
    messagingSenderId: '998694748532',
    projectId: 'zakuska-snack',
    databaseURL: 'https://zakuska-snack.firebaseio.com',
    storageBucket: 'zakuska-snack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHzWERNs0NptvjEhT4qgXj82fX_SMQds',
    appId: '1:998694748532:ios:579b8ad657064bae1bac21',
    messagingSenderId: '998694748532',
    projectId: 'zakuska-snack',
    databaseURL: 'https://zakuska-snack.firebaseio.com',
    storageBucket: 'zakuska-snack.appspot.com',
    iosClientId:
        '998694748532-e5pmqkfdqgeh01fqua7sum9hgvg1ci0d.apps.googleusercontent.com',
    iosBundleId: 'kh.com.pada.rawg',
  );
}
